### ISSUE TITLE
过来开个讨论帖吐槽你的博客233

### ISSUE THREAD

**Issue by Svtter** [Kinice/finalShow#1]
哇哈哈哈哈

**Comment by Kinice** [comment]
我的毕设，各种想法各种牛逼，结果成型一看，特么是个知乎

**Comment by Kinice** [comment]
而且，远明哥特么根本不知道HTML5移动应用是个什么东西，而且特么连Node是啥都不知道，搞得我做WebApp也不是Hybird也不是，艹。

**Comment by Svtter** [comment]
哈哈哈，没事儿，做着自己开心就好

**Comment by Svtter** [comment]
小伙子域名没有备案啊。
233333

**Comment by Kinice** [comment]
都提交管局俩星期了，怎么也得到年后了吧。。而且负责人是我媳妇ヽ(･ω･｡)ﾉ

**Comment by Kinice** [comment]
想看的话用ip访问就能看139.129.30.246

**Comment by Svtter** [comment]
666

**Comment by Svtter** [comment]
木有留言板啊。推disqus，多说~~~~

**Comment by Kinice** [comment]
想自己拿node写一个，包括用新浪微博等发言、评论点赞回复等，之前自己用php做了个小微博系统，觉得可以用node写出来
